RegenerationDelay: 60
LastBedrockY: -60
ItemNBTTag: "PombaChunks"
DurabilityMessage: "&e{CURRENT}/{MAX}"
Blocks:
  Endstone:
    Name: "END_STONE"
    Durability: 3
  Obsidian:
    Name: "OBSIDIAN"
    Durability: 5
  Bedrock:
    Name: "BEDROCK"
    Durability: 10